version: '3.7'

services:
  frontend:
    container_name: frontend
    build: .
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
      - 8082:8082
    stdin_open: true
    # environment:
    #   - CHOKIDAR_USEPOLLING=true
    command: yarn start
    networks:
      - date-ideas-api_date-ideas-backend

networks:
  date-ideas-api_date-ideas-backend:
    external: true
